/**
 * C语言适配器常量定义
 * 包含节点类型映射、查询类型映射等常量
 */

export const C_NODE_TYPE_MAPPING: Record<string, string> = {
  // 函数相关
  'function_definition': 'function',
  'function_declarator': 'function',
  'parameter_declaration': 'parameter',
  'call_expression': 'call',

  // 结构体和类型相关
  'struct_specifier': 'struct',
  'union_specifier': 'union',
  'enum_specifier': 'enum',
  'type_definition': 'type',
  'field_declaration': 'field',
  'array_declarator': 'array',
  'pointer_declarator': 'pointer',
  'field_expression': 'member',
  'subscript_expression': 'subscript',

  // 变量相关
  'declaration': 'variable',
  'init_declarator': 'variable',
  'assignment_expression': 'assignment',

  // 预处理器相关
  'preproc_def': 'macro',
  'preproc_function_def': 'macro',
  'preproc_include': 'include',
  'preproc_if': 'preproc_condition',
  'preproc_ifdef': 'preproc_ifdef',
  'preproc_elif': 'preproc_condition',
  'preproc_else': 'preproc_else',

  // 控制流相关
  'if_statement': 'control_statement',
  'for_statement': 'control_statement',
  'while_statement': 'control_statement',
  'do_statement': 'control_statement',
  'switch_statement': 'control_statement',
  'case_statement': 'control_statement',
  'break_statement': 'control_statement',
  'continue_statement': 'control_statement',
  'return_statement': 'control_statement',
  'goto_statement': 'control_statement',
  'labeled_statement': 'label',
  'compound_statement': 'compound_statement',

  // 表达式相关
  'binary_expression': 'binary_expression',
  'unary_expression': 'unary_expression',
  'update_expression': 'update_expression',
  'cast_expression': 'cast_expression',
  'sizeof_expression': 'sizeof_expression',
  'parenthesized_expression': 'parenthesized_expression',
  'comma_expression': 'comma_expression',
  'conditional_expression': 'conditional_expression',
  'generic_expression': 'generic_expression',
  'alignas_qualifier': 'alignas_qualifier',
  'alignof_expression': 'alignof_expression',
  'extension_expression': 'extension_expression',

  // 字面量和类型
  'comment': 'comment',
  'number_literal': 'number_literal',
  'string_literal': 'string_literal',
  'char_literal': 'char_literal',
  'true': 'boolean_literal',
  'false': 'boolean_literal',
  'null': 'null_literal',
  'type_qualifier': 'type_qualifier',
  'storage_class_specifier': 'storage_class',
  'primitive_type': 'primitive_type',

  // 通用标识符映射
  'identifier': 'identifier',
  'type_identifier': 'type_identifier',
  'field_identifier': 'field_identifier',
  'parameter_list': 'parameter_list',
  'statement_identifier': 'statement_identifier',
  'system_lib_string': 'system_lib_string',
  '_': 'wildcard',
};

export const C_QUERY_TYPE_MAPPING: Record<string, string> = {
  'functions': 'function',
  'structs': 'class',  // 结构体映射为类
  'variables': 'variable',
  'preprocessor': 'expression',  // 预处理器映射为表达式
  'control-flow': 'control-flow',
  'calls': 'call',
  'data-flows': 'data-flow',
  'inheritance': 'inheritance'
};

export const C_SUPPORTED_QUERY_TYPES = [
  // Entity types
  'functions',
  'structs',
  'variables',
  'preprocessor',
  'control-flow',
  // Relationship types
  'calls',
  'data-flows',
  'inheritance',
  // Advanced relationship types
  'concurrency-relationships',
  'control-flow-relationships',
  'lifecycle-relationships',
  'semantic-relationships'
];

export const C_NAME_CAPTURES = ['alias.name',
  'alias.type',
  'alignas.argument',
  'alignof.argument',
  'allocation.function',
  'allocation.size',
  'array.name',
  'array.size',
  'association.pattern',
  'association.result',
  'atomic.compare.function',
  'atomic.desired',
  'atomic.exchange.function',
  'atomic.expected',
  'atomic.fetch.add.function',
  'atomic.fetch.sub.function',
  'atomic.load.function',
  'atomic.memory.order',
  'atomic.store.function',
  'atomic.value',
  'atomic.variable',
  'binary.left',
  'binary.operator',
  'binary.right',
  'bitfield.name',
  'bitfield.size',
  'call.argument',
  'call.function',
  'callback.field',
  'callback.function',
  'callback.variable',
  'cast.type',
  'cast.value',
  'checked.variable',
  'cleanup.function',
  'comma.left',
  'comma.right',
  'comment.any',
  'comment.directive',
  'comment.doc',
  'comment.inline',
  'comment.license',
  'comment.multi',
  'comment.single',
  'comment.special',
  'comment.todo',
  'compiler.barrier.function',
  'compound.operator',
  'concurrency.relationship.atomic.compare',
  'concurrency.relationship.atomic.exchange',
  'concurrency.relationship.atomic.fetch.add',
  'concurrency.relationship.atomic.fetch.sub',
  'concurrency.relationship.atomic.load',
  'concurrency.relationship.atomic.store',
  'concurrency.relationship.compiler.barrier',
  'concurrency.relationship.condition.broadcast',
  'concurrency.relationship.condition.destroy',
  'concurrency.relationship.condition.init',
  'concurrency.relationship.condition.signal',
  'concurrency.relationship.condition.wait',
  'concurrency.relationship.data.dependency',
  'concurrency.relationship.memory.barrier',
  'concurrency.relationship.mutex.destroy',
  'concurrency.relationship.mutex.init',
  'concurrency.relationship.mutex.lock',
  'concurrency.relationship.mutex.trylock',
  'concurrency.relationship.mutex.unlock',
  'concurrency.relationship.rwlock.destroy',
  'concurrency.relationship.rwlock.init',
  'concurrency.relationship.rwlock.readlock',
  'concurrency.relationship.rwlock.unlock',
  'concurrency.relationship.rwlock.writelock',
  'concurrency.relationship.semaphore.destroy',
  'concurrency.relationship.semaphore.init',
  'concurrency.relationship.semaphore.post',
  'concurrency.relationship.semaphore.trywait',
  'concurrency.relationship.semaphore.wait',
  'concurrency.relationship.thread.creation',
  'concurrency.relationship.thread.detach',
  'concurrency.relationship.thread.exit',
  'concurrency.relationship.thread.id',
  'concurrency.relationship.thread.local',
  'concurrency.relationship.thread.wait',
  'concurrency.relationship.tls.get',
  'concurrency.relationship.tls.key.create',
  'concurrency.relationship.tls.key.delete',
  'concurrency.relationship.tls.set',
  'cond.attributes',
  'cond.broadcast.function',
  'cond.destroy.function',
  'cond.handle',
  'cond.init.function',
  'cond.signal.function',
  'cond.wait.function',
  'conditional.alternative',
  'conditional.condition',
  'conditional.consequence',
  'conditional.symbol',
  'control.flow.comma.expression',
  'control.flow.conditional.expression',
  'control.flow.do.while',
  'control.flow.else.if',
  'control.flow.for',
  'control.flow.function.call',
  'control.flow.function.declaration',
  'control.flow.function.definition',
  'control.flow.function.pointer.call',
  'control.flow.goto',
  'control.flow.if',
  'control.flow.if.else',
  'control.flow.label',
  'control.flow.logical.operator',
  'control.flow.loop.break',
  'control.flow.loop.continue',
  'control.flow.nested.if',
  'control.flow.nested.loop',
  'control.flow.recursive.call',
  'control.flow.return',
  'control.flow.seh.leave',
  'control.flow.seh.try.except',
  'control.flow.seh.try.finally',
  'control.flow.short.circuit.and',
  'control.flow.short.circuit.or',
  'control.flow.switch',
  'control.flow.switch.case',
  'control.flow.switch.default',
  'control.flow.while',
  'current.function',
  'data.dependency.function',
  'data.flow.address.assignment',
  'data.flow.array.initialization',
  'data.flow.assignment',
  'data.flow.chained.access',
  'data.flow.compound.assignment',
  'data.flow.conditional.assignment',
  'data.flow.decrement',
  'data.flow.increment',
  'data.flow.initialization',
  'data.flow.macro.call',
  'data.flow.memory.operation',
  'data.flow.parameter.passing',
  'data.flow.pointer.assignment',
  'data.flow.pointer.operation',
  'data.flow.return.value',
  'data.flow.sizeof.assignment',
  'data.flow.struct.initialization',
  'data.flow.type.conversion',
  'data.flow.update',
  'deallocated.pointer',
  'deallocation.function',
  'definition.alignas_qualifier',
  'definition.alignof_expression',
  'definition.array',
  'definition.array.access',
  'definition.assignment',
  'definition.binary_expression',
  'definition.bitfield',
  'definition.boolean_literal',
  'definition.break',
  'definition.cast_expression',
  'definition.char_literal',
  'definition.comma_expression',
  'definition.comment',
  'definition.complex.declaration',
  'definition.compound_expression',
  'definition.conditional_expression',
  'definition.continue',
  'definition.control_statement',
  'definition.enum',
  'definition.expression',
  'definition.extension_expression',
  'definition.field.access',
  'definition.forward.declaration',
  'definition.forward.enum',
  'definition.forward.struct',
  'definition.forward.union',
  'definition.function',
  'definition.function.call',
  'definition.function.pointer',
  'definition.function.pointer.field',
  'definition.function.prototype',
  'definition.function.with_params',
  'definition.generic_expression',
  'definition.goto',
  'definition.include',
  'definition.inline.function',
  'definition.jump_statement',
  'definition.labeled_statement',
  'definition.literal',
  'definition.macro',
  'definition.member.access',
  'definition.modern_feature',
  'definition.nested.struct',
  'definition.null_literal',
  'definition.number_literal',
  'definition.parenthesized_expression',
  'definition.pointer',
  'definition.pointer.member.access',
  'definition.preproc_condition',
  'definition.preproc_else',
  'definition.preproc_ifdef',
  'definition.primitive_type',
  'definition.recursive.call',
  'definition.return',
  'definition.sizeof_expression',
  'definition.storage_class',
  'definition.string_literal',
  'definition.struct',
  'definition.type',
  'definition.type.alias',
  'definition.type_expression',
  'definition.type_modifier',
  'definition.type_qualifier',
  'definition.unary_expression',
  'definition.union',
  'definition.update_expression',
  'definition.variable',
  'do.body',
  'do.condition',
  'doc',
  'documentation.any',
  'enum.constant',
  'enum.name',
  'error.code',
  'error.handling.block',
  'error.value',
  'extension.argument',
  'extern.specifier',
  'extern.variable.name',
  'extern.variable.type',
  'field.name',
  'field.type',
  'file.close.function',
  'file.handle',
  'file.handle.type',
  'file.handle.variable',
  'file.mode',
  'file.open.function',
  'file.path',
  'file.read.function',
  'file.write.function',
  'for.body',
  'for.condition',
  'for.init',
  'for.update',
  'forward.enum.name',
  'forward.struct.name',
  'forward.union.name',
  'function.body',
  'function.name',
  'function.pointer',
  'function.pointer.field',
  'function.pointer.name',
  'function.pointer.type',
  'generic.selector',
  'global.variable.name',
  'global.variable.type',
  'goto.label',
  'identifier',
  'if.body',
  'if.condition',
  'if.else',
  'included.header',
  'index.expression',
  'index.number',
  'index.variable',
  'inline.body',
  'inline.function',
  'inner.struct',
  'inner.struct.name',
  'label.name',
  'label.statement',
  'lifecycle.relationship.file.close',
  'lifecycle.relationship.file.handle.binding',
  'lifecycle.relationship.file.open',
  'lifecycle.relationship.file.read',
  'lifecycle.relationship.file.write',
  'lifecycle.relationship.memory.allocation',
  'lifecycle.relationship.memory.deallocation',
  'lifecycle.relationship.memory.reallocation',
  'lifecycle.relationship.memory.variable.binding',
  'lifecycle.relationship.mutex.destroy',
  'lifecycle.relationship.mutex.init',
  'lifecycle.relationship.mutex.lock',
  'lifecycle.relationship.mutex.unlock',
  'lifecycle.relationship.resource.cleanup',
  'lifecycle.relationship.resource.constructor',
  'lifecycle.relationship.resource.destructor',
  'lifecycle.relationship.resource.init',
  'lifecycle.relationship.scope.global',
  'lifecycle.relationship.scope.local.begin',
  'lifecycle.relationship.scope.local.end',
  'lifecycle.relationship.scope.parameter',
  'lifecycle.relationship.scope.static',
  'lifecycle.relationship.socket.accept',
  'lifecycle.relationship.socket.bind',
  'lifecycle.relationship.socket.close',
  'lifecycle.relationship.socket.create',
  'lifecycle.relationship.socket.listen',
  'lifecycle.relationship.thread.create',
  'lifecycle.relationship.thread.detach',
  'lifecycle.relationship.thread.join',
  'local.variable.name',
  'local.variable.type',
  'macro.function',
  'macro.name',
  'macro.parameter',
  'macro.value',
  'memory.argument',
  'memory.barrier.function',
  'memory.function',
  'memory.order',
  'mutex.attributes',
  'mutex.destroy.function',
  'mutex.handle',
  'mutex.init.function',
  'mutex.lock.function',
  'mutex.trylock.function',
  'mutex.unlock.function',
  'name',
  'name.definition.array',
  'name.definition.assignment',
  'name.definition.enum',
  'name.definition.field',
  'name.definition.function',
  'name.definition.include',
  'name.definition.label',
  'name.definition.macro',
  'name.definition.member',
  'name.definition.pointer',
  'name.definition.preproc_condition',
  'name.definition.preproc_ifdef',
  'name.definition.struct',
  'name.definition.subscript',
  'name.definition.type',
  'name.definition.union',
  'name.definition.variable',
  'nested.field.name',
  'nested.struct',
  'nested.struct.name',
  'new.size',
  'object.name',
  'original.pointer',
  'original.type',
  'param.name',
  'param.type',
  'parameter.name',
  'parameter.type',
  'parenthesized.expression',
  'pattern.class',
  'pattern.field',
  'pattern.method',
  'pattern.type',
  'pointed.type',
  'pointer.field',
  'pointer.name',
  'pointer.variable',
  'preproc_if',
  'reallocation.function',
  'recursive.call',
  'recursive.function',
  'resource.allocation.function',
  'resource.cleanup.function',
  'resource.constructor',
  'resource.deallocation.function',
  'resource.destructor',
  'resource.init.function',
  'resource.parameter',
  'resource.pointer',
  'resource.type',
  'resource.variable',
  'return.expression',
  'rwlock.attributes',
  'rwlock.destroy.function',
  'rwlock.handle',
  'rwlock.init.function',
  'rwlock.readlock.function',
  'rwlock.unlock.function',
  'rwlock.writelock.function',
  'semantic.design.pattern',
  'semantic.relationship.callback.assignment',
  'semantic.relationship.callback.field',
  'semantic.relationship.callback.pattern',
  'semantic.relationship.cleanup.pattern',
  'semantic.relationship.conditional.compilation',
  'semantic.relationship.error.checking',
  'semantic.relationship.error.handling',
  'semantic.relationship.error.return',
  'semantic.relationship.extern.variable',
  'semantic.relationship.function.call',
  'semantic.relationship.function.pointer.type',
  'semantic.relationship.global.variable',
  'semantic.relationship.include',
  'semantic.relationship.macro.definition',
  'semantic.relationship.memory.management',
  'semantic.relationship.pointer.field',
  'semantic.relationship.preprocessor',
  'semantic.relationship.recursive.call',
  'semantic.relationship.resource.initialization',
  'semantic.relationship.struct',
  'semantic.relationship.struct.definition',
  'semantic.relationship.struct.nesting',
  'semantic.relationship.type.alias',
  'semaphore.destroy.function',
  'semaphore.handle',
  'semaphore.init.function',
  'semaphore.initial.value',
  'semaphore.post.function',
  'semaphore.shared',
  'semaphore.trywait.function',
  'semaphore.wait.function',
  'sizeof.argument',
  'socket.accept.function',
  'socket.address',
  'socket.backlog',
  'socket.bind.function',
  'socket.close.function',
  'socket.create.function',
  'socket.domain',
  'socket.handle',
  'socket.listen.function',
  'socket.protocol',
  'socket.type',
  'source.alternative',
  'source.array',
  'source.case.value',
  'source.condition',
  'source.consequence',
  'source.do.block',
  'source.except.condition',
  'source.field',
  'source.field1',
  'source.field2',
  'source.first.condition',
  'source.for.condition',
  'source.for.init',
  'source.for.update',
  'source.function',
  'source.function.name',
  'source.function.pointer',
  'source.index1',
  'source.index2',
  'source.inner.condition',
  'source.label',
  'source.left.expression',
  'source.left.operand',
  'source.object',
  'source.outer.condition',
  'source.parameter',
  'source.return.variable',
  'source.right.expression',
  'source.right.operand',
  'source.second.condition',
  'source.switch.variable',
  'source.try.block',
  'source.variable',
  'source.variable1',
  'source.variable2',
  'source.while.condition',
  'static.specifier',
  'static.variable.name',
  'static.variable.type',
  'struct.name',
  'switch.body',
  'switch.condition',
  'target.array',
  'target.case.block',
  'target.default.block',
  'target.else.block',
  'target.except.block',
  'target.field',
  'target.finally.block',
  'target.first.block',
  'target.for.block',
  'target.function',
  'target.function.body',
  'target.function.pointer',
  'target.if.block',
  'target.index',
  'target.inner.block',
  'target.label',
  'target.labeled.statement',
  'target.method',
  'target.object',
  'target.pointer',
  'target.recursive.function',
  'target.second.block',
  'target.short.circuit.function',
  'target.switch.block',
  'target.type',
  'target.variable',
  'target.while.block',
  'target.while.condition',
  'thread.argument',
  'thread.attributes',
  'thread.create.function',
  'thread.detach.function',
  'thread.exit.function',
  'thread.exit.value',
  'thread.function',
  'thread.handle',
  'thread.id.function',
  'thread.join.function',
  'thread.local.specifier',
  'thread.local.type',
  'thread.local.variable',
  'thread.return.value',
  'thread.start.function',
  'thread.wait.function',
  'tls.destructor',
  'tls.get.function',
  'tls.key',
  'tls.key.create.function',
  'tls.key.delete.function',
  'tls.set.function',
  'tls.value',
  'type.name',
  'unary.argument',
  'unary.operator',
  'update.argument',
  'update.operator',
  'variable',
  'variable.name',
  'while.body',
  'while.condition'];

export const C_BLOCK_NODE_TYPES = [
  'compound_statement', 'function_definition', 'if_statement', 'for_statement',
  'while_statement', 'do_statement', 'switch_statement', 'struct_specifier', 'union_specifier'
];

export const C_FUNCTION_NODE_TYPES = [
  'function_definition',
  'function_declarator'
];

export const C_MODIFIERS = [
  'static',
  'extern',
  'const',
  'volatile',
  'inline',
  'register',
  'auto',
  'restrict',
  '_Atomic',
  'thread_local',
  '_Noreturn',
  '_Thread_local',
  '__attribute__'
];

export const C_COMPLEXITY_KEYWORDS = [
  { keyword: 'pointer', pattern: '*', weight: 1 },
  { keyword: 'static', pattern: 'static', weight: 1 },
  { keyword: 'extern', pattern: 'extern', weight: 1 },
  { keyword: 'const', pattern: 'const', weight: 1 },
  { keyword: 'volatile', pattern: 'volatile', weight: 1 },
  { keyword: 'member_access', pattern: '->|\\.', weight: 1 },
  { keyword: 'sizeof', pattern: 'sizeof', weight: 1 },
  { keyword: 'memory_management', pattern: 'malloc|free', weight: 1 },
  { keyword: 'multithreading', pattern: 'thread|mutex', weight: 2 },
  { keyword: 'signal_handling', pattern: 'signal', weight: 1 }
];